# Generated by Django 2.2 on 2020-12-09 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='Description',
            new_name='description',
        ),
    ]
